language: android
android:
  components:
    - tools
    - android-25
    - build-tools-25.0.1
    - platform-tools
    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

jdk:
  - oraclejdk8

before_install:
 - chmod +x gradlew

script:
   - ./gradlew build connectedCheck

after_failure: "cat $TRAVIS_BUILD_DIR/app/build/outputs/lint-results-debug.xml"